name: Flutter

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release 
      - name: Install the Netlify CLI
        run: npm install netlify-cli -g
      - name: Update the release number
        run: perl -p -i -e 's/<!-- Release _ -->/<!-- Release ${{ github.run_number }} -->/g' ./build/web/index.html
      - name: Deploy the website
        run: netlify deploy --prod --dir ./build/web --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --timeout=600 --message "Deployed on $(date)"