name: Flutter

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release
      - run: mv ./build/web ./dist
      - uses: actions/configure-pages@v3
      - name: Deploy to github pages
        run: |
          ls -la
          ls -la ./dist
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git branch gh-pages
          git rm -r --cached .
          git add -f ./dist
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages