name: Flutter

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: ./build/web
  deploy:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v3
      - uses: actions/download-artifact@v2
        with:
          name: web
          path: ./build
      - name: Deploy to github pages
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git branch gh-pages
          git rm -r --cached 
          git add -f ./build/web/*
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
