name: Flutter

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: ./build/web
  deploy:
    runs-on: self-hosted
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v3
      - uses: actions/download-artifact@v2
        with:
          name: web
          path: ./build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          name: web
      - run: ls -la
      - run: ls -la build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          PAGES_DIR: ./build/web